# Generated by Django 4.2.3 on 2023-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
