# Generated by Django 4.2.3 on 2023-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
