# Generated by Django 4.2.3 on 2023-08-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='index',
            new_name='order',
        ),
    ]
