# Generated by Django 4.2.3 on 2023-08-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_video_completed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_completed_by',
            new_name='video_viewed_by',
        ),
    ]
