# Generated by Django 4.2.3 on 2023-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_length'),
        ('jwt_auth', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses_started',
            field=models.ManyToManyField(blank=True, related_name='started_by', to='courses.course'),
        ),
    ]
