# Generated by Django 4.2.3 on 2023-08-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_index'),
        ('jwt_auth', '0005_alter_user_courses_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='videos_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='videos.video'),
        ),
    ]
