# Generated by Django 4.2.3 on 2023-08-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_user_videos_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='videos_completed',
        ),
    ]
