# Generated by Django 4.2.3 on 2023-08-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_remove_user_videos_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses_completed',
        ),
    ]
