# Generated by Django 4.2.3 on 2023-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('trailer_url', models.URLField(max_length=1000)),
                ('video_url', models.URLField(max_length=1000)),
                ('CE_credits', models.IntegerField(max_length=8)),
                ('images', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='courses', to='categories.category')),
                ('instructors', models.ManyToManyField(related_name='courses', to='instructors.instructor')),
            ],
        ),
    ]
