# Generated by Django 4.2.3 on 2023-07-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CE_credits',
            field=models.IntegerField(),
        ),
    ]
