# Generated by Django 4.2.3 on 2023-07-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_images_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trailer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
