# Generated by Django 4.2.3 on 2023-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_trailer_alter_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
