# Generated by Django 4.2.3 on 2023-08-07 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_course_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='courses_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
