# Generated by Django 4.2.3 on 2023-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=10000)),
                ('profile_picture', models.CharField(max_length=10000)),
                ('linkedin_url', models.URLField(max_length=10000)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
